name: SSPANEL 面板签到

on:
  workflow_dispatch:
  schedule:
    - cron: "35 23 * * *"
  watch:
    types: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: 安装依赖包
        run: |
          npm install

      - name: "开始执行"
        run: |
          node sspanel_checkin.js
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          SITE_URL: ${{ secrets.SITE_URL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
