name: SSPANEL 面板签到

on:
  workflow_dispatch:
  schedule:
    - cron: "35 23 * * *"
  watch:
    types: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: 安装依赖包
        run: |
          npm install

      - name: "开始执行"
        run: |
          # node sspanel_checkin.js
          node https://raw.githubusercontent.com/sudojia/sspanel_checkin/master/sspanel_checkin.js
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          SITE_URL: ${{ secrets.SITE_URL }}
